#!/usr/bin/env bash
set -euo pipefail

# create-droplet.sh — Provision a new Docker droplet in the League Students team.
#
# Usage:
#   ./digital-ocean/create-droplet.sh <number>    e.g. ./digital-ocean/create-droplet.sh 3 → docker3
#
# Prerequisites:
#   - doctl installed (`brew install doctl`)
#   - DO_LEAGUE_STUDENT_TOKEN exported in your shell (see config.env for details)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

NUMBER="${1:-}"

if [[ -z "$NUMBER" ]]; then
  echo "Usage: $0 <number>"
  echo ""
  echo "  Creates a droplet named ${DROPLET_NAME_PREFIX}<number>"
  echo "  Example: $0 3  →  ${DROPLET_NAME_PREFIX}3"
  exit 1
fi

if ! [[ "$NUMBER" =~ ^[0-9]+$ ]]; then
  echo "ERROR: Argument must be a number, got '$NUMBER'"
  exit 1
fi

require_do_token

DROPLET_NAME="${DROPLET_NAME_PREFIX}${NUMBER}"
APPS_DOMAIN="apps${NUMBER}.${R53_DOMAIN_BASE}"
DOCTL="doctl --access-token $DO_LEAGUE_STUDENT_TOKEN"

: "${DO_REGION:=sfo3}"
: "${DO_SIZE:=s-2vcpu-4gb}"
: "${DO_IMAGE:=docker-20-04}"
: "${DO_SSH_KEYS:?Set DO_SSH_KEYS in config.env (SSH key ID or fingerprint)}"
: "${DO_TAGS:=student-project}"
: "${DO_PROJECT_ID:=""}"

echo "==> Creating droplet: $DROPLET_NAME"
echo "    Team:    Students (The League)"
echo "    Project: App Deployment"
echo "    Domain:  *.$APPS_DOMAIN"
echo "    Region:  $DO_REGION"
echo "    Size:    $DO_SIZE"
echo "    Image:   $DO_IMAGE"
echo "    Tags:    $DO_TAGS"
echo ""

# Check if droplet already exists
if $DOCTL compute droplet list --format Name --no-header | grep -qx "$DROPLET_NAME"; then
  echo "ERROR: Droplet '$DROPLET_NAME' already exists."
  echo "       Use 'doctl compute droplet list' to see existing droplets."
  exit 1
fi

# Create the droplet
$DOCTL compute droplet create "$DROPLET_NAME" \
  --region "$DO_REGION" \
  --size "$DO_SIZE" \
  --image "$DO_IMAGE" \
  --ssh-keys "$DO_SSH_KEYS" \
  --tag-names "$DO_TAGS" \
  --enable-monitoring \
  --enable-backups \
  --wait

echo ""
echo "==> Droplet created. Fetching details..."

# Get the new droplet's ID and public IP
DROPLET_INFO=$($DOCTL compute droplet list --format Name,ID,PublicIPv4 --no-header \
  | awk -v name="$DROPLET_NAME" '$1 == name { print $2, $3 }')
DROPLET_ID=$(echo "$DROPLET_INFO" | awk '{ print $1 }')
DROPLET_IP=$(echo "$DROPLET_INFO" | awk '{ print $2 }')

# Assign to the App Deployment project
if [[ -n "$DO_PROJECT_ID" ]]; then
  echo "==> Assigning droplet to App Deployment project"
  $DOCTL projects resources assign "$DO_PROJECT_ID" \
    --resource "do:droplet:$DROPLET_ID"
fi

if [[ -z "$DROPLET_IP" ]]; then
  echo "WARNING: Could not retrieve IP. Check: doctl compute droplet list"
  exit 1
fi

# --- Generate server directory ---
SERVER_DIR="$SCRIPT_DIR/servers/$DROPLET_NAME"
echo "==> Generating server config at digital-ocean/servers/$DROPLET_NAME/"

mkdir -p "$SERVER_DIR"

cat > "$SERVER_DIR/server.env" <<ENV
# $DROPLET_NAME — Server info (generated by create-droplet.sh)
DROPLET_NAME="$DROPLET_NAME"
DROPLET_NUMBER="$NUMBER"
DROPLET_IP="$DROPLET_IP"
APPS_DOMAIN="$APPS_DOMAIN"
ENV

cat > "$SERVER_DIR/setup-local.sh" <<'SETUP_SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

# setup-local.sh — Configure your local machine to access this server.
#
# This script:
#   1. Copies the deploy key to ~/.ssh/do-deploy-key (if not already there)
#   2. Adds an SSH config entry for this server
#   3. Creates a Docker context for this server
#
# After running, you can:
#   ssh <server>                              # SSH into the server
#   docker context use <server>               # switch Docker to this server
#   DOCKER_CONTEXT=<server> docker ps         # one-off command on the server

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/server.env"

# Find the deploy key (in the digital-ocean dir, two levels up)
DO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
SOURCE_KEY="$DO_DIR/deploy-key"
DEST_KEY="$HOME/.ssh/do-deploy-key"

echo "==> Setting up local access to $DROPLET_NAME ($DROPLET_IP)"
echo "    Domain: *.$APPS_DOMAIN"
echo ""

# --- Step 1: Deploy key ---
if [[ -f "$DEST_KEY" ]]; then
  echo "  Deploy key already at $DEST_KEY"
else
  if [[ -f "$SOURCE_KEY" ]]; then
    cp "$SOURCE_KEY" "$DEST_KEY"
    chmod 600 "$DEST_KEY"
    echo "  Copied deploy key to $DEST_KEY"
  else
    echo "ERROR: Deploy key not found at $SOURCE_KEY"
    echo "       Ask your instructor for the deploy-key file and place it at:"
    echo "       $SOURCE_KEY"
    exit 1
  fi
fi

# --- Step 2: SSH config ---
SSH_CONFIG="$HOME/.ssh/config"

if grep -q "^Host $DROPLET_NAME\$" "$SSH_CONFIG" 2>/dev/null; then
  echo "  SSH config entry for '$DROPLET_NAME' already exists"
else
  mkdir -p "$HOME/.ssh"
  touch "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG"

  cat >> "$SSH_CONFIG" <<SSH_ENTRY

# $DROPLET_NAME — DigitalOcean Docker server (*.$APPS_DOMAIN)
Host $DROPLET_NAME
    HostName $DROPLET_IP
    User root
    IdentityFile $DEST_KEY
    IdentitiesOnly yes
SSH_ENTRY

  echo "  Added SSH config entry: Host $DROPLET_NAME → $DROPLET_IP"
fi

# --- Step 3: Docker context ---
if docker context inspect "$DROPLET_NAME" >/dev/null 2>&1; then
  echo "  Docker context '$DROPLET_NAME' already exists"
else
  docker context create "$DROPLET_NAME" \
    --docker "host=ssh://$DROPLET_NAME"
  echo "  Created Docker context: $DROPLET_NAME"
fi

echo ""
echo "==> Done! You can now:"
echo "  ssh $DROPLET_NAME                             # SSH into the server"
echo "  docker context use $DROPLET_NAME              # switch Docker to this server"
echo "  DOCKER_CONTEXT=$DROPLET_NAME docker ps        # list containers on the server"
echo ""
SETUP_SCRIPT

chmod +x "$SERVER_DIR/setup-local.sh"

echo ""
echo "==> Droplet '$DROPLET_NAME' is ready at $DROPLET_IP"
echo ""
echo "Next steps:"
echo "  1. Set up DNS:"
echo "       ./digital-ocean/dns-route53.sh $NUMBER"
echo "  2. Set up Caddy and Docker networking:"
echo "       ./digital-ocean/setup-server.sh $NUMBER"
echo "  3. Configure your local machine (SSH + Docker context):"
echo "       ./digital-ocean/servers/$DROPLET_NAME/setup-local.sh"
echo "  4. Test the setup:"
echo "       ./digital-ocean/test-server.sh $NUMBER"
echo ""
